* An interface for Spotify without recommendation
** Pedantic manifesto
I do not like being shown recommendations / suggestions when I do not
ask for them. I do not like that it takes away agency from me. I do
not think it is particularly conductive to me discovering new things.

Discovering new things comes from exploration. Exploration is a
coherent journey through new places. Going on a journey is impossible
if there is no structure to move through.

Pages filled with recommendations give you things without exploration,
they get you to the end of the journey directly, with all the rewards
given to you. But without the journey, they are meaningless.

As such (but not only for this reason), Spotify's interface is
anathema to me. This project aims at providing a replacement for it.

** Short term goals of the project
*** TODO Hack together an interface for Spotify that allows to control the player and search for music
DEADLINE: <2021-10-03 zo>
:PROPERTIES:
:Effort:   1d
:END:
*** TODO See if I like it
DEADLINE: <2021-12-03 vr>
*** TODO See if other people like it
DEADLINE: <2021-12-03 vr>
*** TODO Iterate?

